### ISSUE TITLE
UI issue when updating random schedule max/min values

### ISSUE THREAD

**Issue by kmac** [kmac/mindfulnotifier#11]
The logic to keep the max/min values consistent is faulty. Sometimes the min value gets set to the same as the max value.

Workaround: Set the max value first, hit the enter key, Then set the min value.

**Comment by wolftune** [comment]
related: it seemed that when I disabled and re-enabled, it reset the min back to 45 (I had set it to less)

**Comment by kmac** [comment]
Yeah it's odd behaviour. I haven't really bothered to investigate and fix. Will try to figure it out over the next week or two.

**Comment by kmac** [comment]
Fixed in Release 1.0.14+23
