### ISSUE TITLE
Syncing Reminders between devices

### ISSUE THREAD

**Issue by trymeouteh** [kmac/mindfulnotifier#12]
I have a suggestion for syncing reminders between devices.

Please add a setting for the reminders to be saved and read from TXT files inside a directory of the users choice such as Internal/MindfulReminder/ Inside this directory is where TXT files of every reminder is saved and the app will read this directory for TXT files to display reminders. Users can use any syncing app they want such as Syncthing, MEGA, Nextcloud, etc to have these TXT files sync between another device. This way when you add a reminder to one device it will automatically be added to your other devices.

**Comment by kmac** [comment]
This is in fact already mostly supported via the export / import functionality. It is somewhat manual in that you have to do the export/import manually but adding a sync service into this app is out of it's scope. I also think that reminders probably won't change very much once each user fine-tunes their own reminder set.

One of my goals is simplicity, and in line with that I want to avoid any internet access. This way users can be sure they are not being spied on in any way.

**Comment by trymeouteh** [comment]
I do not expect a syncing service to be added to the app, I think the user has to choose a syncing service like Syncthing but for this to work, the reminders need to be stored in a directory as TXT file which the app will read.

**Comment by kmac** [comment]
Unfortunately from what I've been reading, Google has been file system access for apps, unless the app is specifically targeted at managing files. I've received notification that I have to remove the legacy external storage access by May 5th (which is in the next update). I'll leave this open for now but it's not looking very promising.

**Comment by kmac** [comment]
Note that with the changes to backup/restore in 1.0.11 you can now share the backup to a cloud service, syncthing, etc. I've tried it out using syncthing and Google Drive. The restore should let you select the file from the same place. I know it's a little more manual than what you're looking for, but it should be a relatively process now.

**Comment by kmac** [comment]
The changes in Release 1.0.14+23 are aimed around more easily organizing reminders, and the reminder lists can now either be merged or replaced via the export/import function (this has changed to be more geared towards just the reminders now - it's no longer a full backup and restore). With the file system limitations in Android 11 I won't be spending any time on doing any sort of automatic sync.
