### ISSUE TITLE
Search and tagging

### ISSUE THREAD

**Issue by GEkuL** [kmac/mindfulnotifier#15]
The more quotes I'm adding to the app the more time I need to find them.

Could you add the **search option**  and finding on hashtags.

It would drastically increase the usability of the app.

**Comment by kmac** [comment]
I've uh, only tested this with maybe 20 quotes. So you may be breaking new ground. Let me know if you run into any issues. It's not exactly optimized for a large number of quotes, e.g. even the randomness is achieved by shuffling the entire list.
As for this issue, this type of feature would probably be quite some work to implement. I'll leave this open but it's not really on my radar at the moment.

**Comment by kmac** [comment]
I'm not sure I'll ever have a search function, but I am testing changes to support tagging. The reminder list can be filtered by tag. See comment in #20

**Comment by kmac** [comment]
I think I've covered off your usability concerns with Release 1.0.14+23. There's no search, but with tags it's easier to organize and find things. If you're using hashtags you may want to export your reminders, manually edit the JSON file and replace the hashtag with the tag field.
