### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by GEkuL** [kmac/mindfulnotifier#16]
It could be a good thing to add share option in notification and somewhere in front of the quote in "Reminders"

So if people added the quote and after that got it it in notification, they could easily share it with friends.

It would be really nice!

**Comment by kmac** [comment]
I can't add it directly to the notification unfortunately - the library I'm using doesn't have an option for multiple actions on a notification. However, I can probably do something where clicking the notification will take you to the main screen where there would be some option to share. Does that sound okay?

**Comment by GEkuL** [comment]
@kmac well, that's definitely better than nothing :blush: . Yeah, I would appreciate that!)

**Comment by kmac** [comment]
Added in 1.0.13. Long-press on main screen to open the share dialog.
