### ISSUE TITLE
hide next reminder

### ISSUE THREAD

**Issue by takiainen** [kmac/mindfulnotifier#17]
I'd like to have an option to not know when is the next reminder. One of the most important joys of this kind of app is not knowing when the bell will play.

Please add an option to hide "next reminder.." -text.

**Comment by kmac** [comment]
Okay yes. I mainly added that bottom status line for debugging. I think what I'll do is have an option to turn that entire bottom status line off. At the same time removing the option to 'add extra debugging info' because it's outlived it's usefulness.
Thanks for the feedback.

**Comment by kmac** [comment]
Added in 1.0.12 which will be released soon.
