### ISSUE TITLE
Silence notifications when Do not disturb is set

### ISSUE THREAD

**Issue by zigmhount** [kmac/mindfulnotifier#21]
Hello,
First, thanks for this app, simple idea but I really like it.
However, during my workday I want to be able to silence most notifications on my phone at once for a period of time, but setting Do Not Disturb to Priority Only or Alarms Only does not silence MindfulNotifier (but Total Silence does).

I'm on Android 7 (LineageOS-based /e/, [this build](https://images.ecloud.global/dev/athene/)), and I already set the priority of MindfulNotifier's notifications to "No full screen interruptions, peeking, sound or vibration", so I'm not sure why this app believes it is more important than e.g. social network apps :)

I tried instead to just disable it with the setting on the main window, but I was surprised to see that this also doesn't have an effect. I can raise a different issue for this if you prefer. I just tried to reproduce it and didn't manage though, it might only re-enabled itself after some time...

Let me know if you need more details!
Cheers

**Comment by kmac** [comment]
Hi, thanks for raising this. I'm on lineage but android 10-based, and I noticed that I'm seeing this as well. I thought it was just my DND settings. It's a bit odd to me, because it should be the same as 'media' settings. I'll see what I can find.

**Comment by kmac** [comment]
Fixed in 1.0.13. Thanks for reporting! Let me know if you still have issues.

**Comment by zigmhount** [comment]
Thank you so much for fixing this!
