### ISSUE TITLE
tag selector

### ISSUE THREAD

**Issue by wolftune** [kmac/mindfulnotifier#26]
Tags are great, thanks! But after they exist, adding the same tag to a reminder requires typing it out (or pasting). It should have a dropdown to choose from the existing tags with a "new tag" option.

**Comment by kmac** [comment]
Yeah, it's actually supposed to autocomplete but I know that's not working yet. I just wanted to get the bulk of the update in in the meantime... I'll take a look and see what I can get it to do. Some sort of drop-down of existing tags plus the open text field would be ideal.

**Comment by kmac** [comment]
"Fixed" in 1.0.15. I spent too much time trying to get the new flutter Autocomplete widget to work (and looked at other libraries). So in the end I just added a separate drop-down to choose from existing tag. Or you can edit the text field beside that to add a new tag or rename a tag.

I may revisit this in the future once the Autocomplete widget matures (right now it doesn't support setting an initial value, which is a killer).
