### ISSUE TITLE
Import is not working.

### ISSUE THREAD

**Issue by pepedelosbosques** [kmac/mindfulnotifier#33]
Simple test steps:
1) Export
2) Delete one reminder
3) Import (Nothing seems to happen)

**Comment by kmac** [comment]
I can't reproduce this issue at all. 

Here's what I am seeing on my phone and in emulator:

Steps:
- Export
- Move exported file to Downloads
- Delete an entry. Also tried deleting a disabled entry.
- Import with either 'Merge' option or 'Replace' option
- The deleted item is back.

Can you provide a bit more details? Are you doing a 'merge' or 'replace'?  Which version are you using? Device and android version? Thanks!

**Comment by pepedelosbosques** [comment]
Android 10.3.11
Version 1.0.16

I have no dialog or anything else as soon I click on the file I want to import. Then I land at home screen of mindful Notifier.

**Comment by pepedelosbosques** [comment]
Version 1.0.17:29. Same issue

**Comment by kmac** [comment]
Sounds like maybe a storage permissions issue.

**Comment by pepedelosbosques** [comment]
It's enabled. I removed it, and the app ask for the permission as expected. 

Don't sure if it related to permissions, since I'm able to browse the files and select one.

**Comment by kmac** [comment]
I have no clear idea what the issue might be here. What phone are you using?  I'm wondering if it's a small screen, which might be crashing the dialog if it can't fit the widgets into it.
Any chance you can get a logcat fle? That would show the issue. I've been using the MatLog app. It's a bit tricky to setup if you don't have root (you need to use adb). If you get that going, then filter on 'flutter' and it will capture the relevant logs.

**Comment by pepedelosbosques** [comment]
Early today I reboot my phone. Minutes ago I read your comment and I tried to import again to get the logs ... it worked ... not sure why. The dialog is visible now and I could import without problems. It's a oneplus, with big screen. Can't say if the reboot helped this time.  

Thanks for your support. Think you could close this issue, and take it into account if it happens again.

**Comment by kmac** [comment]
Hmm, odd. I suspect it may be something with the flutter app lifecycle on upgrade. It's something to watch for but I'm not going to try to track it down right now. Thanks for getting back to me on this one.

**Comment by easyKL** [comment]
Please reopen.
On Lineage OS 13 a dialogue is prompted when tapping on the Import button.
On Lineage OS 9 nothing happens, although Export button proceeds with action, and Storage permission is granted (no permissions denied)

version 1.0.24
