### ISSUE TITLE
Add 45 minutes period option

### ISSUE THREAD

**Issue by daiwai** [kmac/mindfulnotifier#42]
It would be nice to have 45 as one of the minute options

**Comment by kmac** [comment]
Yeah I can try to add this in. I had this in before, but I was having some issues with where to align the 45m interval on startup so I gave up on it at the time. I'll just align it to something like the next 15 minute mark (i.e, :00, :15, :30, :45). 

Note that for the time being you could set your schedule to random and use 45/45. It just won't be aligned on any particular start time.

**Comment by daiwai** [comment]
Thanks for the quick reply and the hint about the random mode, that works for my use case.

I can see how it is not immediately obvious how to auto-align the 45 schedule but I agree with you the next full quarter hour makes the most sense :+1:

**Comment by kmac** [comment]
I'm testing some changes here which would allow an arbitrary interval (to the minute). I think I have it but it needs more testing.

**Comment by kmac** [comment]
Period options now have granularity of a minute. Please let me know if you see issues with this since I usually run in random mode.
