### ISSUE TITLE
Can't add new reminder

### ISSUE THREAD

**Issue by ssssamstrup** [kmac/mindfulnotifier#51]
Everything seems to work, but when pressing »Add« nothing happens.

![Screenshot_20220113-122146](https://user-images.githubusercontent.com/4302516/149321499-561c8152-e6e3-4fff-a0fc-a30d626713ef.png)

**Comment by kmac** [comment]
Do you mind pasting that text in a comment here?  So that I can copy and paste it into my test VM.
I expect there's an issue with unicode.

**Comment by ssssamstrup** [comment]
The issue has disappeared and I've just tried writing the text and adding it again, which worked fine.
