### ISSUE TITLE
Audio reminders but without message notifications

### ISSUE THREAD

**Issue by m-col** [kmac/mindfulnotifier#56]
Hi there, absolutely loving this app, thank you for making it.

I've enjoyed getting the messages at first but I've found that I've stopped paying attention to them (somewhat ironic, perhaps) and I just remove them right away. As far as I can tell, it isn't possible to disable the messages while still getting the periodic audio bells. Is this correct? Would this be something that could be supported?

**Comment by m-col** [comment]
Just to add, I'm not requesting that you work on it (unless you feel compelled to and it's a trivial change!), I realise the onus is on me to submit the feature(s) I want, and hopefully at some point I manage to do so!

**Comment by GEkuL** [comment]
Hello mate,
Actually, I didn't get your question, what are you asking?
In fact you can disable the notifications or stop the app. Also you can download the bell as your ringtone and set it for timer or some kind of app for such purposes.

**Comment by m-col** [comment]
To clarify, I'd like to continue using the periodic tones but disable the text notifications only.

> Also you can download the bell as your ringtone and set it for timer or some kind of app for such purposes.

Yeah good idea, just playing sounds is general enough maybe there is a random timer app or something I could hook up to that audio file. Thanks!
